### ISSUE TITLE
Enabling Bank Tag Layouts causes large FPS lag.

### ISSUE THREAD

**Issue by oqkr** [geheur/bank-tag-custom-layouts#47] opened 2021-11-24 18:05 UTC
#### Error log
https://pastebin.com/Wb6djX37

#### Issue Description
For about a day now, when BankTagLayouts plugin is enabled, FPS plummets from over 50 FPS to 3 to 4 fps within a few seconds. Multiple errors for this plugin specifically can be seen in the RuneLite client log linked above.

The issue does not occur in safemode, and I tested turning off all third-party plugins then turning them back on one at a time. So far, this plugin does seem to be cause.

It may be an problem on just my system related to some sort of misconfiguration, so please let me know if you need any additional information on my setup if this can't be reproduced elsewhere.

Thank you!

**Comment by R-Y-M-R** [comment] 2021-12-16 02:57
Same problem here.

**Comment by geheur** [comment] 2021-12-16 03:09
The issue is inventory setups with colons `:` in their names not working right. Until I fix it the best option is to remove any colons from any inventory setups.

**Comment by hjdarnel** [comment] 2021-12-23 02:46
I've noticed the same.  When I remove colons from names, it gets a bit better, but I'm still going from 90 to 65 fps (generally reproducible by hovering items in my inventory.)

**Comment by geheur** [comment] 2021-12-28 01:37
Should be fixed in 1.4.11. Not sure about the issue not related to colons in the name reported by @hjdarnel but I've made some optimizations that might make that better.

**Closed by geheur** 2021-12-28 01:37 UTC
