### ISSUE TITLE
Bank Tag Layouts reset when changing the name of your Inventory Tag setup

### ISSUE THREAD

**Issue by mrwhisker23** [geheur/bank-tag-custom-layouts#72] opened 2023-03-19 16:35 UTC
For example: I have numbers in my Inventory Setups for stages of my farm run like "(4) Hespori". If I rename this to "(3) Hespori" I have to rearrange all my items again because the layout preset is tied to the name of the Inventory Setup. If you change the name back to what it was before, the old layout returns.

Before changing the name (and after reverting it):
![image](https://user-images.githubusercontent.com/7873992/226190333-8df9ee87-4e28-4bea-b25c-1924ffde41a9.png)

After changing the name:
![image](https://user-images.githubusercontent.com/7873992/226190353-a462d5d5-47f0-4432-bd37-da3fa6ec1d63.png)

**Comment by Nick2bad4u** [comment] 2023-04-17 13:49
Same thing has been happening to me. Thanks for reporting, hopefully it gets fixed!

**Comment by geheur** [comment] 2023-05-04 23:26
Duplicate of #21.

**Closed by geheur** 2023-05-04 23:26 UTC
