### ISSUE TITLE
degraded items

### ISSUE THREAD

**Issue by yourmumisgayaf** [geheur/bank-tag-custom-layouts#15] opened 2021-04-05 18:41 UTC
degraded items like barrows equipment stops showing up in the tag after it has degraded to next stage

**Comment by geheur** [comment] 2021-04-05 19:58
If you added the barrows items to the tab using auto-layout, then that is an interesting issue because I'd have to add something to figure out which items should automatically have variants added (such as barrows items) vs which ones should not, as described in #13.

If you added the barrows items to the tab by dragging them onto the tab or editing the barrows items' tags, then that is something you should solve through bank tags either using "*" or holding shift while dragging the item onto the tab.

Closing cause this is sort of a duplicate of #13.

**Closed by geheur** 2021-04-05 19:58 UTC
