### ISSUE TITLE
Odd scroll behavior on long bank tabs

### ISSUE THREAD

**Issue by Memebeams** [geheur/bank-tag-custom-layouts#43] opened 2021-11-07 14:30 UTC
Issue: When viewing a large layout, the bank does not correctly remember your scroll position when closing and reopening.

Reproduction steps:
1. Make a layout.
2. Add a lot of items to the layout.
3. Have a lot of empty spaces in the layout.
4. Scroll to the bottom of the layout.
5. Close the bank.
6. Open the bank.

Expected behavior: Bank opens with layout open to where you were previously scrolled (the bottom, in this case).

Actual behavior: Bank opens with layout open and scrolled to roughly halfway down the layout.

Example layout that causes this behavior (I was working on this herblore tab when I discovered the issue):
```
banktaglayoutsplugin:herblore training,15196:0,15197:1,15198:2,15198:3,15199:4,15199:5,15199:6,15200:7,249:8,251:9,253:10,253:11,15218:12,15218:13,15218:14,15219:15,227:16,227:17,227:18,227:19,227:20,227:21,227:22,227:23,3040:24,19380:25,3032:26,3034:27,97:28,97:29,97:30,19291:31,235:32,225:33,221:34,5952:35,5954:36,15242:37,1975:38,239:39,2428:40,15265:41,113:42,2444:43,169:44,3008:46,121:48,19347:49,115:50,3010:54,15203:56,15199:57,15200:58,15201:59,15201:60,15202:61,15202:62,15202:63,2998:64,15218:65,15219:66,15220:67,15220:68,261:69,261:70,261:71,227:72,227:73,227:74,227:75,227:76,227:77,227:78,227:79,97:81,19291:82,101:83,101:84,103:85,103:86,103:87,231:90,221:91,235:92,231:93,2970:94,2434:98,2436:99,2448:100,3016:102,139:106,145:107,181:108,3018:110,15204:112,15204:113,3051:114,15205:115,15206:116,217:117,15206:118,219:119,15223:120,15223:121,3000:122,15224:123,2481:124,2481:126,269:127,227:128,227:129,227:130,227:131,227:132,227:133,227:134,227:135,19295:136,19295:137,3004:138,107:139,2483:140,2483:142,225:144,15251:145,15242:146,239:147,15251:148,3138:150,247:151,2440:152,3024:154,2442:155,2452:156,157:160,3026:162,163:163,2454:164,15203:168,2998:169,5935:170,6049:172,15203:175,15201:176,15220:177,5935:178,5075:182,2998:183,21163:184,6016:185,5935:186,15242:188,15252:190,227:191,233:192,5935:194,6018:196,15196:200,15197:201,15198:202,15199:203,229:207,249:208,251:209,253:210,15218:211,1939:216,1939:217,1939:218,1939:219,10145:227,banktag:herblore training,23835,2152,3004,3000,3008,3042,3040,3049,3032,3034,3026,3024,3010,3018,3016,3051,83,97,99,95,91,21163,2481,2485,2483,6470,6472,21622,6016,6018,121,115,113,592,107,105,103,101,6049,163,157,2998,145,139,2970,133,10111,127,3408,199,181,189,10145,169,3410,1939,243,241,239,235,233,231,229,227,225,223,-139,1975,221,219,217,215,213,5075,211,207,205,203,201,209,-181,-175,269,9017,9018,265,263,261,-163,259,257,255,253,251,249,247,245,5945,2434,2432,2430,5942,5943,2436,5935,2428,2454,2452,2450,2444,2442,2440,5951,5952,5954,2448,3138,9736
```

**Comment by Wynadorn** [comment] 2021-11-08 19:03
Is this the issue you're talking about?
https://www.youtube.com/watch?v=mpqmKI1slHE
I haven't found a solution for it yet either.

**Comment by geheur** [comment] 2021-11-08 23:47
I don't think video 1 shows the same issue @Wynadorn. video 2 shows this issue though.

Your flashing-on-withdrawing issue from video 1 is not layouts-unique; it happens with bank tags when the remove tab separator config item is set. Idk what causes it, I blame unlock fps! I was hoping someone at runelite would fix it in bank tags so I could copy their solution, but maybe I'll have to look into it myself.

this issue is a duplicate of #17.

**Comment by Wynadorn** [comment] 2021-11-09 15:09
I've tried to test the issue from Video 1 a bit further. it seems to be issue https://github.com/runelite/runelite/issues/12406 which was sort-of fixed in PR https://github.com/runelite/runelite/pull/12466

Video 3: https://www.youtube.com/watch?v=GYTL1_ssAsQ

The game's FPS does seem to make a difference, limiting the game to 15 stops the issue  from appearing. Though I suspect the low framerate prevents it from being visible. Maybe it occurs more in FPS intensive areas such as the grand exchange, where the framerate is unstable.

However when using a regular tag tab the items in the tab will remain in place, you can still see the scrollbar jumping to the top and back. For some reason Layout Tag Tabs have both the items and scrollbar jumping to the top, which hinters usability.

I'm not familiar with the code from either plugin myself, however I hope the changes made in that PR point to a possible cause/solution,

**Comment by geheur** [comment] 2021-11-10 06:36
@Wynadorn what do you mean "sort-of fixed"?

**Comment by Wynadorn** [comment] 2021-11-10 08:42
> @Wynadorn what do you mean "sort-of fixed"?

Because the scroll bar still jumping to the top for a couple frames I assumed that the scroll position is still lost, even in regular tag tabs. However a workaround has been implemented which restores the position afterwards.

**Comment by Memebeams** [comment] 2021-11-10 08:52
> Is this related to the Issue you're talking about? https://www.youtube.com/watch?v=mpqmKI1slHE I haven't found a solution for it yet either.
> 
> Edit: https://www.youtube.com/watch?v=5SmCefCjW7g here's a second clip with opening / closing the bank.

Yeah, at least Video 2 seems correct, like @geheur said.

**Comment by geheur** [comment] 2021-11-10 09:03
@Wynadorn so, the only "sort-of fix" that this did for bank **tags** is that it flickers Other than that, it works properly? 

As for the flickering, I have made https://github.com/runelite/runelite/pull/14359 which I think I will need to fix this issue in layouts.

**Comment by Wynadorn** [comment] 2021-11-10 09:07
> @Wynadorn so, the only "sort-of fix" that this did for bank **tags** (not layouts but the vanilla runelite plugin) is that it flickers? Other than that, it works properly?
> 
> As for the flickering, I have made [runelite/runelite#14359](https://github.com/runelite/runelite/pull/14359) which I think I will need to fix this issue in layouts.

Yep, bank **tags** has a scrollbar that flickers, bank **layouts** has flickering items & scrollbar

**Comment by geheur** [comment] 2021-11-10 11:17
Fix for both issues on fix-scrollbar-flickering branch, requires that runelite PR to work.

**Closed** 2021-12-24 21:49 UTC
